"""Shared path constants for the pipeline.

Layout:
  data/raw/       cached external inputs (git-ignored, regenerated by `make raw`)
  data/derived/   everything a script computes (git-ignored, regenerated by `make data`)
  figures/        committed figure outputs (regenerated by `make figures`)
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
RAW = DATA / "raw"
DERIVED = DATA / "derived"
FIG = ROOT / "figures"
MANUSCRIPT = ROOT / "manuscript"

WIPO_RAW = RAW / "wipo" / "wipo-data-patent-indicators"

for _d in (RAW, DERIVED, FIG):
    _d.mkdir(parents=True, exist_ok=True)
