"""The numbers.json registry and the manuscript orphan scanner.

`Registry` is the single place a computed quantity is recorded. Each entry carries:
  value    - the number as recomputed from raw/derived data by check_numbers.py
  claimed  - the number as it currently appears in the manuscript (None if not yet in prose)
  tol      - absolute tolerance for value vs claimed
  printed  - the string form(s) that may legitimately appear in the manuscript
  unit, note

check_numbers.py builds a Registry, asserts value≈claimed for every entry, writes
numbers.json, then scans Paper A/main.tex for numeric tokens that no entry accounts for.
"""
import json
import re

from _paths import ROOT

TEX_FILES = [
    ROOT / "Paper A" / "main.tex",
]

NUMBERS_JSON = ROOT / "numbers.json"
ALLOW_FILE = ROOT / "Paper A" / "numbers_allow.txt"
WAIVER_FILE = ROOT / "Paper A" / "numbers_waivers.txt"
TEX = ROOT / "Paper A" / "main.tex"

_NUM_TOKEN = re.compile(r"\d{1,3}(?:,\d{3})+(?:\.\d+)?|\d+(?:\.\d+)?")
_MONTHS = ("January|February|March|April|May|June|July|August|September|October|November|December")


def _printed_forms(value):
    """Plausible manuscript spellings of a number: with and without thousands commas,
    and a few rounded decimal lengths."""
    forms = set()
    if value != value or value in (float("inf"), float("-inf")):
        return []          # NaN/inf: nothing is printed, record() reports it instead
    if value == int(value):
        i = int(round(value))
        forms |= {str(i), f"{i:,}"}
    for nd in (0, 1, 2, 3):
        s = f"{abs(value):.{nd}f}"
        if float(s) == 0 and value != 0:
            continue
        forms.add(s)
        if "," not in s and abs(value) >= 1000:
            forms.add(f"{abs(value):,.{nd}f}")
    return sorted(forms)


class Registry:
    def __init__(self):
        self.entries = {}
        self.failures = []      # (key, claimed, value, tol, note) - block a push
        self.waived = []        # (key, claimed, value, tol, note, reason) - reported, non-blocking

    def record(self, key, value, claimed=None, tol=0.0, unit="", note="", printed=None):
        if key in self.entries:
            raise KeyError(f"duplicate numbers key: {key}")
        value = float(value)
        claimed = None if claimed is None else float(claimed)
        tol = float(tol)
        # A quantity that has become undefined -- an empty data slice after a
        # methodology change -- must fail loudly rather than crash the gate or slip
        # through as "no claim to check".
        if value != value:
            self.entries[key] = {"value": None, "claimed": claimed, "tol": tol,
                                 "unit": unit, "note": f"UNDEFINED (no data): {note}",
                                 "printed": sorted(set(printed or []))}
            self.failures.append((key, claimed, float("nan"), tol,
                                  f"{note} -- recomputes to no data at all"))
            return value
        forms = set(printed or [])
        forms |= set(_printed_forms(value))
        if claimed is not None:
            forms |= set(_printed_forms(claimed))
        entry = {
            "value": round(value, 4),
            "claimed": None if claimed is None else round(claimed, 4),
            "tol": tol,
            "unit": unit,
            "note": note,
            "printed": sorted(forms),
        }
        self.entries[key] = entry
        if claimed is not None and abs(value - claimed) > tol:
            waivers = _load_waivers()
            if key in waivers:
                self.waived.append((key, claimed, value, tol, note, waivers[key]))
            else:
                self.failures.append((key, claimed, value, tol, note))
        return value

    def external(self, key, value, source, unit="", note="", printed=None):
        """A number quoted from a cited third-party source, not produced by this pipeline.
        Recorded in numbers.json (with its source) so the orphan scanner accounts for it;
        never recomputed. A human verifies these against the source (ground rule 7)."""
        self.record(key, value, claimed=value, tol=0.0, unit=unit,
                    note=f"[external: {source}] {note}", printed=printed)

    def note_only(self, key, value, unit="", note="", printed=None):
        """A quantity that is recomputed and exposed for the orphan scanner but has no
        fixed manuscript claim to assert against (e.g. an intermediate)."""
        return self.record(key, value, claimed=None, unit=unit, note=note, printed=printed)

    # ---- outputs -----------------------------------------------------------
    def write_json(self):
        payload = {
            "_comment": "Single source of truth for every numeric claim. "
                        "Generated by pipeline/check_numbers.py - do not edit by hand.",
            "entries": dict(sorted(self.entries.items())),
        }
        NUMBERS_JSON.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

    def all_printed(self):
        out = set()
        for e in self.entries.values():
            out |= set(e["printed"])
        return out

    # ---- orphan scan -----------------------------------------------------
    def orphan_scan(self):
        existing = [p for p in TEX_FILES if p.exists()]
        if not existing:
            return [], "no manuscript tex files"
        allow_lits, allow_res = _load_allow()
        known = self.all_printed() | allow_lits
        orphans = []
        for tex in existing:
            text = tex.read_text(encoding="utf-8")
            # Preamble only defines macros; a data claim can only live in the body.
            text = text.split(r"\begin{document}", 1)[-1]
            for ender in (r"\section*{References}", r"\bibliographystyle", r"\printcredits"):
                if ender in text:
                    text = text.split(ender)[0]
                    break
            text = re.sub(r"(?<!\\)%.*", "", text)
            for noise in (
                r"\\def\\(floatpagepagefraction|textpagefraction)\{[^}]*\}",
                r"\\includegraphics\[[^\]]*\]",
                r"\\(email|ead)\{[^}]*\}",
                r"p\{[0-9.]+cm\}",
                r"\{[0-9.]+(cm|pt|em|in|\\textwidth)\}",
                r"\\rule\{[^}]*\}\{[^}]*\}",
                r"\\(inst|item|ref|label|cite)\{[^}]*\}",
                r"\\(title|author)running",
                r"\\hline|\\\\",
                r"(Section|Sections|Figure|Figures|Fig\.?|Table|Tables)~?\s*\d+(\.\d+)?",
                r"\bRQ\s*\d+",
                r"ASEAN-\d+",
                rf"\d{{1,2}}\s+({_MONTHS})\s+\d{{4}}",
                r"IP/C/W/\d+",
            ):
                text = re.sub(noise, " ", text)
            for m in _NUM_TOKEN.finditer(text):
                tok = m.group(0)
                if tok in known:
                    continue
                if any(rx.fullmatch(tok) for rx in allow_res):
                    continue
                ctx = text[max(0, m.start() - 45): m.end() + 45].replace("\n", " ")
                orphans.append((tok, f"[{tex.name}] {ctx.strip()}"))
        return orphans, None


def _load_waivers():
    out = {}
    if not WAIVER_FILE.exists():
        return out
    for line in WAIVER_FILE.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if not line or "|" not in line:
            continue
        key, reason = line.split("|", 1)
        out[key.strip()] = reason.strip()
    return out


def _load_allow():
    lits, res = set(), []
    if not ALLOW_FILE.exists():
        return lits, res
    for line in ALLOW_FILE.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        if line.startswith("re:"):
            res.append(re.compile(line[3:].strip()))
        else:
            lits.add(line)
    return lits, res
